CREATE TABLE ONLINESTOREDB.BKP_Regions AS Select * from ONLINESTOREDB.Regions;
CREATE TABLE ONLINESTOREDB.BKP_Countries AS Select * from ONLINESTOREDB.Countries;
CREATE TABLE ONLINESTOREDB.BKP_Locations  AS Select * from ONLINESTOREDB.Locations;
CREATE TABLE ONLINESTOREDB.BKP_Warehouses  AS Select * from ONLINESTOREDB.Warehouses;
CREATE TABLE ONLINESTOREDB.BKP_Product_category  AS Select * from ONLINESTOREDB.Product_category;
CREATE TABLE ONLINESTOREDB.BKP_Products  AS Select * from ONLINESTOREDB.Products;
CREATE TABLE ONLINESTOREDB.BKP_Inventory  AS Select * from ONLINESTOREDB.Inventory;
CREATE TABLE ONLINESTOREDB.BKP_Department  AS Select * from ONLINESTOREDB.Department;
CREATE TABLE ONLINESTOREDB.BKP_Employees  AS Select * from ONLINESTOREDB.Employees;
CREATE TABLE ONLINESTOREDB.BKP_Customer  AS Select * from ONLINESTOREDB.Customer;
CREATE TABLE ONLINESTOREDB.BKP_Contacts  AS Select * from ONLINESTOREDB.Contacts;
CREATE TABLE ONLINESTOREDB.BKP_Orders  AS Select * from ONLINESTOREDB.Orders;
CREATE TABLE ONLINESTOREDB.BKP_OrderItems  AS Select * from ONLINESTOREDB.OrderItems;



