--------------------------------------------------------
--  File created - Friday-February-11-2022   
--------------------------------------------------------
REM INSERTING into ONLINESTOREDB.COUNTRIES
SET DEFINE OFF;
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (1,'India',1);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (2,'Nigeria',2);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (3,'Ghana',2);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (4,'Kenya',2);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (5,'Japan',1);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (6,'China',1);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (7,'France',6);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (8,'Italy',6);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (9,'Germany',6);
Insert into ONLINESTOREDB.COUNTRIES (COUNTRYID,COUNTRYNAME,REGION) values (10,'Greece',6);
