Create user ADMIN IDENTIFIED BY ADMINUSER#123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT DBA TO ADMIN;

CREATE USER APPUSER IDENTIFIED BY APPUSER123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO APPUSER; 

GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Regions TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Countries TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Locations TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Warehouses TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Product_category TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Products TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Inventory TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Department TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Employees TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Customer TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Contacts TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.Orders TO APPUSER;
GRANT INSERT, UPDATE, DELETE, INSERT ON ONLINESTOREDB.OrderItems TO APPUSER;